### ISSUE TITLE
Upgrade to Tailwind v3

### ISSUE THREAD

**Issue by nemanjapetrovic** [tailwindtoolbox/Screenshot-Landing-Page#2]
Hi, 

I've tried upgrading this page to the latest version of Tailwind CSS and the whole page messes up. Will we get this project upgraded to the latest version of the Tailwind?

Thank you!

**Comment by tailwindtoolbox** [comment]
Hey, I've updated it to use the latest v2 cdn link... but it should work fine when you setup v3 as it will use the JIT engine?

How are you using it in your project?

**Comment by nemanjapetrovic** [comment]
Sorry, I didn't load properly v3 of tailwind css and that is why I was thinking the page was messed up.

I've just tried and it works, I've updated the line https://github.com/tailwindtoolbox/Screenshot-Landing-Page/blob/06acdd34bac08ca81781609ce582ac01caf657bf/index.html#L15 with the following:

```
<script src="https://cdn.tailwindcss.com"></script>
```

which is cdn link for v3 of tailwind css I get the following result:

The differences I could identify:

 - some text is diffrent
 - orange button color is missing
 - some cards are thinner

everything else seems ok to me.

![image](https://user-images.githubusercontent.com/15672932/148834433-b1b9690c-8980-4726-adf1-d9a862ac1cd1.png)
